# 
# RECIPEDIA PLUGIN DOCUMENTATION
# please read completely before proceed with config at bottom, for unique time
# 
# 
# PLUGIN DESCRIPTION
# 
# Recipedia is a rewrite and replacement of RecipeSearch, with CB 1.13+ support
# and other fixes, enhancements and additions.
# 
# Recipedia was inspired on many recipes plugins as Craftipedia, RecipesGUI,
# Essentials ("/recipe" command) and similar, bringing the best of each with
# some original additional features as: localized item name searches supported
# by client language files, inverse recipes search (with item as ingredient),
# recipes for held item, recipes for targeted block or entity, amongst others.
# 
# 
# BRIEF
# 
# I hate to Alt-Tab to search recipes online while i am playing. I was an avid
# user of these mentioned plugins on my server and suggested many features but
# was never heard, sadly the new vanilla "recipe book" sucks and those plugins
# are now dead, so i wrote my own and now i want to share it with you.
# 
# I am not a java expert, i did the best i could, so this plugin could still
# have some bugs (backup your server often, i warned you so i am not
# responsible for damages), so if you are sure you found one please report it,
# ask your doubt or post your suggestion or translation at the project page:
#
# - https://dev.bukkit.org/projects/recipedia/
# 
# 
# HOW TO GET LOCALIZED ITEM NAME SEARCH TO WORK
# 
# Recipedia supports search items by keywords. In addition to Material names
# it also supports localized item names by adding compatibility with Minecraft
# client language files. It is designed this way so any server admin could
# add his preferred language(s) just by extracting files from client
# and copy (them) to the plugin folder.
# 
# Some advantages of this are: customization, flexibility, stability throught
# version changes, and the unconcern of no needing a dedicated dev staff to
# generate language files. I am aware many similar plugins died due this (with
# the additional consideration that i am a little lazy :D ).
# 
# 
# LANGUAGE FILES INSTALLATION / UPDATING FROM MINECRAFT CLIENT
# 
# In this example i will tell you how to install the "Espanol (Espana)" (es_es)
# language file from Minecraft 1.13 windows client, however you can install
# many variants of same language to cover the subtle differences beetween them.
# 
# Please use files matching with version since plugin has no way to guess it,
# note since minecraft 1.13 the language file format had changed to json:
# 
# - Open file "%APPDATA%\.minecraft\assets\indexes\<version>.json" with a text
#   editor (for example in my case the file is "1.13.json")
# 
# - Search for string "minecraft/lang/<lang>.json" ("minecraft/lang/es_es.json"
#   in my case) (note in previous versions they had ".lang" extension)
# 
# - Take note of the hash in the value next (mine is
#   "ba31825a8666b744facf483538afd7a398408d05")
# 
# - Write down the first 2 characters of the hash ("ba" in this case)
# 
# - Go to the folder "%APPDATA%\.minecraft\assets\objects\<2 chars>
#   (replace <2 chars> with mentioned above)
# 
# - In that folder, locate the file named before the previously mentioned hash
#   (i.e. "ba31825a8666b744facf483538afd7a398408d05")
# 
# - Copy the file to Recipedia plugin folder,
#   i.e. "<bukkit folder>/plugins/Recipedia/"
# 
# - Rename the copied file to its original supposed name ("es_es.json" in my
#   case), note the ".json" extension is important for plugin to find it.
#   I also recommend to include version in file name like "es_es-1.13.json"
# 
# - Repeat the process with other locales if you want, then restart or reload
#   the server to apply changes
# 
# 
# SPECIAL CASE: DEFAULT LANGUAGE FILE "en_us.json"
# 
# Instead of located in "assets" folder, the default language file
# "English (US)" (en_us) is hardcoded inside the game executable, but i also
# recommend to extract and install by the way described below for
# wikis-compilant names and players that like us-english item names:
# 
# - Open the file "%APPDATA%\.minecraft\versions\<version>\<version>.jar" with
#   some compression utility like 7-Zip, PeaZip, WinRar, WinZip or similar
# 
# - Inside file, browse to the folder "assets\minecraft\lang\"
# 
# - Locate the file "en_us.json", extract it and copy to the plugin folder.
#   I also recommend to include version in file name like "es_us-1.13.json"
# 
# - Restart or reload the server to apply changes
# 
# 
# PLUGIN PERMISSIONS (default: true, always true for ops)
# 
# - recipedia.search     : search items by name, typing keywords
# - recipedia.hand       : list recipes for item held in main hand
# - recipedia.target     : list recipes for block or entity behind crosshair
# - recipedia.ingredient : search inverse recipes with item as ingredient
# - recipedia.recipe     : display recipes drawn in a temp crafting grid


# PLUGIN CONFIGURATION
# just some translations, for non ascii chars please use unicode escapes


# item tooltip messages, use '%s' to print referenced string variable

recipesCount: "%s Recipes"
ingredient: Ingredient
fuel: Fuel
pageNumber: Page %s
CraftShapedRecipe: Shaped Recipe
CraftShapelessRecipe: Shapeless Recipe
CraftFurnaceRecipe: Furnace Recipe
CraftBlastingRecipe: Blasting Recipe
CraftCampfireRecipe: Campfire Recipe
CraftSmokingRecipe: Smoking Recipe
CraftStonecuttingRecipe: Stonecutting Recipe


# search items status messages, use '%s' to print related variable

resultsCount: "%s Items Found"
noRecipesFound: No recipes found for selected item, block or entity
noItemsFound: The keywords didn't match any item, please relax your search
tooManyResults: Too many results, please refine your search
noPermission: You don't have the permission '%s'


# help pages, 10 lines with 54 columns max recomended, test before release it
# lines are yellow, until find a colon which turn it cyan
# use %1$s and %2$s to print installed languages and player permissions

helpPage: |
  Recipedia, search recipes ingame! (no more Alt-Tab + Web):
  /recipedia <keywords>: search recipes by item name [/r]
  /recipehand: show recipes for item held in main hand [/rh]
  /recipetarget: show recipes for targeted block or entity [/rt]
  * left click item: show recipes / browse search result pages
  * right click item: list inverse recipes (with item as ingredient)
  * click outside: left click: back / right click: exit
  Installed Languages: %1$s
  Your permissions: %2$s
  More info: http://dev.bukkit.org/projects/recipedia